// TesterKey.h — the PUBLIC half of the Low End test-key signing pair. Generated by
// scripts/tester-key.js; safe to commit, since it can only check keys, never make
// them. See TesterGate.h.
#pragma once

namespace lowend::tester {
inline constexpr const char* kModulusHex =
    "a6060883a1b777d731a0f5782eac6f6c1b3047e28841adfd106c0d1ee531ade3"
    "9e578849ac7501c867481adf0458194352b27401839e1916c8b429f0254e6a72"
    "3f5c135683c8bf545dec945bcc736635f74617f8d12739b5707f2af8d5510617"
    "534959ea19ba53fac1c3476aeb869e367363dcc4f1936e9b89ef510a9442f8bd"
    "e3e12db679651ff793fd732c0ec825dc494d5a597e87d8fb067c2ac151690697"
    "ddc62157447e4931b29a09cdbaa83843be5c9c5cc1c68c883a4f89e0334ad380"
    "5a86bf176d2162c962f4e59f0e5b156d01e64f7e64efc946f3b686af9933315e"
    "57ef1b80efc9cf23320f8e6d9df498470450843c5e712442ba33be875f6d4969";
}
