// TesterVectors.h — GENERATED by scripts/make-tester-test-vectors.js. Do not edit.
// Tokens signed by a throwaway key pair (the private half was discarded); see that script.
#pragma once
namespace testervectors {
constexpr long long kIssuedMs = 1789948800000LL;   // 2026-09-21T00:00:00Z
constexpr long long kGoodExpiresMs = 1792540800000LL;
constexpr long long kExpiredExpiresMs = 978307200000LL;
inline constexpr const char* kModulus =
    "ac47369e2eb61eb8f3278b07cb32e456fabd41fb789e8d0c966c07e4dc27c930746847f975beebcc9cb56e8f6c47f454"
    "c9ef9afeb1637e9b83b61f8d94e6f1d7891c529cf32d959bf2fa629f5cdf41968828a5c92c80f48dce8465a8357b6574"
    "d6febe6ce3eb1587cfe487908e85b4c59b5652f69a61790e0d7eb76b80f823d83c46ea2fc30bcf978f9f9df4d6f3ed23"
    "b6d9a68da3ac1aaefd0d9bd33602380cdead43942118cdd902721f06ad1f42569bfefb8057340f1ddfdbf94aa27d38fa"
    "5ff07e8e30d802378aa58ac04725063d5718ec5dd70aa1ec3f46ca50e004c6fc12be3cbd6684ddd44fe0676f76a50c1a"
    "928a3b02cd424914645058fb930a3067";
inline constexpr const char* kOtherModulus =
    "d5b2b91ff483ebfb51163e28135ad28bf09df34c96ea7316df90240bdcf0e044649c9836300fc4fd9bec6b8d4c51725b"
    "4446dc197e134cb6ee31bec5f5313bb4de04ceb7d3e600cd5c6fd530014604673796426303d7b33d49c8199b08907489"
    "f3d283f4dd703ae00e664bc12f5ad9ca840d0501a3912cdb899b19744f00e477bf297e04583f0e9c696697072c49fb73"
    "91770bff6741ea4da28e016d7277ad36781e857b352b833cbfb556c7c0740f694bb4f7695385f9279feb91fc0e613aef"
    "03cc21d31701a13f80a171904692f0a88e11eeca2c204b04e27dac9965a3c4b5401b0f567badbf5efcef82487fd21348"
    "69496df3c5445a67116574443b0c092d";
inline constexpr const char* kGood =
    "eyJhIjoibG93ZW5kLXRlc3RlciIsImkiOjE3ODk5NDg4MDAwMDAsImUiOjE3OTI1NDA4MDAwMDAsIm4iOiIwYTBiMGMwZCJ9"
    ".dMjeVD-oxIJnjonk9D9KAWduzDEfs_ERwzP1z9Iu2x_RC6hEH9HcE-sOtvFK9p_t5XyHoliAEdpLnNDWiCG5PSTx7QKr8Z7"
    "R_zTZysiebiyGsXQjn0H9CfwZGQm8aBhydK5z8FHIdVC65bXIraI5P635V1qOt5QF4zs7aUeNBPecJsouBJ4JYDZuFKKxk33"
    "DLwJPapE2nz0VS95L3So2-QtTCWZbsYgWtjEapQu90MSmCc7klsQrCbSas1k2cKfHq57kreqynrCTulvLU4N5LFPeCo7Nalu"
    "ukffDf3ULAtvTMzxpU-E9_1hT_vF_dXkg7Usfnu54eLtIp5_TPYMurg";
inline constexpr const char* kLong =
    "eyJhIjoibG93ZW5kLXRlc3RlciIsImkiOjE3ODk5NDg4MDAwMDAsImUiOjQxMDI0NDQ4MDAwMDAsIm4iOiIwMTAyMDMwNCJ9"
    ".T0hs4v0wWRhNVmSBWY2nI8qBYPcubkGDr3lPVu-IXs0wdJL_HSOk7pSYPYWmwIcNyDTHvSwpZ2_rdWIixEDwraQQw3o-khO"
    "_TWIV1RWR27VeK3mQKBoQpcsU3J4MwHoIq_o-B70krbGUbfWBe6JYkER7o5AbcsgcW1yVYXdVOraeuRART1PIXif4qK_zfi8"
    "bMDNx14eQI_e6yMQJmti76yCfdg63m2_wLpltei3lf4ydT9_PKf5Trb76lW76mj-JZbDcvCrxNndfQYL0D-Xxs0y4c2LJt4v"
    "X2NBu9XUbod0CPzqhjIt5edjCwOCgU906PSGA5_mJPtaVe71bwGaBdw";
inline constexpr const char* kExpired =
    "eyJhIjoibG93ZW5kLXRlc3RlciIsImkiOjk3NTcxNTIwMDAwMCwiZSI6OTc4MzA3MjAwMDAwLCJuIjoiMTExMTExMTEifQ.E"
    "kLIJDF3AYHhtF2H0iHeRBmStco4SQoxvXb2hHJk1Qe-wDfnbjf5CdfgWWo1TqPd3VanH8HqBBbB4SJDTL1dbeuSVRMKSjsGo"
    "KHA0PAFLlZIA-lOvjNhkCkrLRfdWd4j-Vuf3KFMcyx27QbG0nOKeELAK7_6p6mZ0BYof5wLyDIUH930ay5Ky_V5YvW9r-kjL"
    "7xVojudG-uY7VvM5-UN-uwJSf7IZPuqKjmjOtFYXn9D_K1KwI5LBX8Z8QUrwwwlKDSm15qexGK3Rv8jIriwbl3d2i9LIt8Wm"
    "KzzY1-RpciSw__jsqO1oztpMVgM5G4NROro9C5r4PcBHKrgmgIosQ";
inline constexpr const char* kFromFuture =
    "eyJhIjoibG93ZW5kLXRlc3RlciIsImkiOjQwOTk4NTI4MDAwMDAsImUiOjQxMDI0NDQ4MDAwMDAsIm4iOiIyMjIyMjIyMiJ9"
    ".kD8IhSkpahnsISIM0XKQ7nBZDbgi-xxjdwo3ycKwT3Nh5OFcZ0HkvIkNsNKeaNK5cVI1A06tfBDJpL1cW0kH0qpS7cpm36w"
    "mhUVcxfvXGjMzgvwkgDm_-030elrsXJqajz4q8dyWN2pBEHFBVeLiTUevRlgxa9rMyz7gvMwUhlGMQKpTowl1bM_23KXhF65"
    "rP8Oap5XrrvYaoY1APyyqxkhXln_zBKfnL3SIsV2t9MC4XOctwOaZ3c72QVhQ0V7EJ1VKPCa16WykQyuBTjxBT4nGWa3wJQk"
    "tPMe7AK_n0lGSrDVSfq1gLUOAJyqdZ99EBcnWLs0I11Dl4DsT21pzCg";
inline constexpr const char* kWrongProduct =
    "eyJhIjoic29tZXRoaW5nLWVsc2UiLCJpIjoxNzg5OTQ4ODAwMDAwLCJlIjo0MTAyNDQ0ODAwMDAwLCJuIjoiMzMzMzMzMzMi"
    "fQ.ku5_oohy5qQApKUh7WHRHBMIG2ILM_eCVbhaZzaI4ujG1LHton3-y5c9KSEyZsSb-JMMgkm09p-PQfcFAyRTiMiZgsytQ"
    "ofIuAFqB2eEF5hRcPfPXwUzWixiycq-2D1ZaQvkb2dspY4UFaK0p_qHoZylkkv4uUWDp6a1aNxautAeM6QeSPYGcvV3DukCI"
    "LAObRlmfGQ_jJcaC3TVtZR4f-Dg1qNDQ8R8CUgNHcFx9f3KYziCSj9h91dz-AM-yRZYlWlWkbBzssU-mpBUjfO7zmtgKpus_"
    "ix0OMQ9pnGCI2xuZ91lGhkIApOoWoHC5Zf5AuzdKgxglKnO5cIf5z-3Pg";
inline constexpr const char* kNoDates =
    "eyJhIjoibG93ZW5kLXRlc3RlciIsIm4iOiI0NDQ0NDQ0NCJ9.Db8ux6RXFOoBx6hDVKA-18-HPbChklCBs64fUmW5eotrUbX"
    "EgHYfYqbdmC2_lAL01YgvoOKtWsQJseAVqpwIcmrMc1-dmeO3y7uM3DjNqElq65zJICxUco2IsrbtyDEdMOApmMw86EMeoKq"
    "_xsTsx7BL9XU2JMH31EvU5M2FAdi1veGDuPEt8-LUBW3tyCPYCuLzATVa-H81Rvi7J6vG_h3nxRgIcYIHGRgJioQmV7Ps_QA"
    "uflwOh5NlCzfA3KiIOVaQSPISd2is73uWdEHtx4Vxm0K7GG0kGnEAJxPf3m_Vtkmum637RrboMoGntIytEZ4Jp71EbJIt46r"
    "wLynANw";
inline constexpr const char* kBackwardsDates =
    "eyJhIjoibG93ZW5kLXRlc3RlciIsImkiOjQxMDI0NDQ4MDAwMDAsImUiOjE3ODk5NDg4MDAwMDAsIm4iOiI1NTU1NTU1NSJ9"
    ".EsTd2YYo0pDayDkBJRA2CpxzAiwc7f-gPuKwH6Qm6WiUYkWJMhUKis7MIIk-3xJ_uO1Nfzr3bTDudi2nz0KTaoBjoJmEd_n"
    "DZyvfKsiuOUMyXYY0bqkh0D2OnuWa1C1cBzjQ_ZY0tXCUc54Ii1OY9zXPvvJ0_sGY2x0YKFVnbnJ2p4-idP83T1TCZv-36dz"
    "7KS2qxiMK1WmzOUS5TuwbKLKt6vk6ck1Cf0G6L5UMqodJ1gxtkyP6StyQyFse2IzOFQiZiac5E_ALW21dys9gHxhzdA41-hN"
    "0uaB2Hq3qQHYSjcfJtmaTJxIBnSuR17OH42qg7hm049YQYQF1hhxAoQ";
inline constexpr const char* kSignedByOther =
    "eyJhIjoibG93ZW5kLXRlc3RlciIsImkiOjE3ODk5NDg4MDAwMDAsImUiOjQxMDI0NDQ4MDAwMDAsIm4iOiI2NjY2NjY2NiJ9"
    ".FL4QKa7nj8udZ8l4qBSNxXud36QNFHnYNwlxQKRXCOAGDvq7SSh9b2LkJc9uyCX6EBEY0POnPwDTO9nyHlq97OU9NJYSV6U"
    "uH2Lz2fHVYbdJJ6gVsZgg630RpK891FfK1LezYqR9Q9HPfbXyu62F9jJphlF3VEqINBeanzM1ZU7vZkPY52-3iDEs_RsIQHA"
    "alIDekSM2U3TiAqeIUvcYeVVovevSWnnF3HBan_R3MzXI2fKGNythQVimcpAlQlIuF-32SiJU4NXG57zGJj3jqLzcahvUQtq"
    "3vB9eJEVXRUsFTv54D3zh26yjgj0_Nhfio7_EoQt1H0LY2r9TtBxdXA";
}
