#!/usr/bin/env node
// tester-key.js — makes and checks the Low End TEST key. Not the studio's licensing.
//
//   node tester-key.js init                  one-off: makes the signing key pair
//   node tester-key.js issue [--days 30]     prints a key that works for everyone, then stops
//   node tester-key.js verify <key>          says what a key contains and whether it is still good
//
// The PRIVATE half of the pair lives in
//     Documents\Amanorsac Studio\Security\LowEnd-Tester\tester-private.pem
// (or wherever LOWEND_TESTER_DIR points) and is never written into the repository:
// whoever holds it can issue keys. The PUBLIC half is written into
// src/plugin/TesterKey.h and compiled into test builds, which is all a build needs.
//
// If the private key is lost, no more keys can be issued for builds that carry the
// old public key; run `init --force` to make a new pair and build again. Test keys
// cannot be revoked: a key stops working only when its own expiry date passes.
'use strict';
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');

const PRODUCT = 'lowend-tester';
const DAY = 86400000;
const dir = process.env.LOWEND_TESTER_DIR ||
  path.join(os.homedir(), 'Documents', 'Amanorsac Studio', 'Security', 'LowEnd-Tester');
const privPath = path.join(dir, 'tester-private.pem');
const headerPath = path.join(__dirname, '..', 'src', 'plugin', 'TesterKey.h');

const args = process.argv.slice(2);
const cmd = args[0];
const flag = (name, def) => { const i = args.indexOf('--' + name); return i >= 0 ? args[i + 1] : def; };
const b64u = b => Buffer.from(b).toString('base64url');
const die = m => { console.error(m); process.exit(1); };

function loadPrivate() {
  if (!fs.existsSync(privPath)) die(`No signing key at ${privPath}. Run: node tester-key.js init`);
  return crypto.createPrivateKey(fs.readFileSync(privPath));
}
function modulusHex(pub) {
  return Buffer.from(pub.export({ format: 'jwk' }).n, 'base64url').toString('hex');
}

if (cmd === 'init') {
  if (fs.existsSync(privPath) && !args.includes('--force')) die(`A signing key already exists at ${privPath}. Use --force to replace it (keys issued with the old one stop working in new builds).`);
  fs.mkdirSync(dir, { recursive: true });
  const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048, publicExponent: 65537 });
  fs.writeFileSync(privPath, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 });
  const n = modulusHex(publicKey);
  fs.writeFileSync(headerPath,
`// TesterKey.h — the PUBLIC half of the Low End test-key signing pair. Generated by
// scripts/tester-key.js; safe to commit, since it can only check keys, never make
// them. See TesterGate.h.
#pragma once

namespace lowend::tester {
inline constexpr const char* kModulusHex =
    "${n.match(/.{1,64}/g).join('"\n    "')}";
}
`);
  console.log('Signing key written to  ' + privPath);
  console.log('Public key written to   ' + headerPath);
  console.log('Keep the first file safe and out of the repository.');
} else if (cmd === 'issue') {
  const days = Number(flag('days', '30'));
  if (!(days > 0 && days <= 365)) die('--days must be between 1 and 365.');
  // --start back-dates the key (e.g. --start 2026-01-01) so an EXPIRED key can be
  // made on purpose, to check what a tester sees when theirs runs out.
  const now = flag('start') ? Date.parse(flag('start')) : Date.now();
  if (Number.isNaN(now)) die('--start must be a date such as 2026-01-01.');
  const body = JSON.stringify({ a: PRODUCT, i: now, e: now + days * DAY, n: crypto.randomBytes(4).toString('hex') });
  const sig = crypto.sign('sha256', Buffer.from(body), loadPrivate());        // RSA PKCS#1 v1.5
  const key = b64u(body) + '.' + b64u(sig);
  const when = new Date(now + days * DAY);
  fs.appendFileSync(path.join(dir, 'issued.log'),
    `${new Date(now).toISOString()}  ${days} days  expires ${when.toISOString()}\n${key}\n\n`);
  console.log(key);
  console.error(`\nExpires ${when.toUTCString()}  (${days} days from now).`);
} else if (cmd === 'verify') {
  const raw = (args[1] || '').replace(/\s+/g, '');
  const [b, s] = raw.split('.');
  if (!b || !s) die('That is not a test key.');
  const pub = crypto.createPublicKey(loadPrivate());
  const ok = crypto.verify('sha256', Buffer.from(b, 'base64url'), pub, Buffer.from(s, 'base64url'));
  console.log('signature:', ok ? 'valid' : 'NOT VALID');
  if (ok) {
    const v = JSON.parse(Buffer.from(b, 'base64url').toString());
    console.log('issued:   ', new Date(v.i).toUTCString());
    console.log('expires:  ', new Date(v.e).toUTCString(), Date.now() >= v.e ? '(expired)' : `(${Math.ceil((v.e - Date.now()) / DAY)} days left)`);
  }
} else {
  die('Usage: node tester-key.js init | issue [--days 30] | verify <key>');
}
